#!/bin/bash

. $MY_BIN/photos/dvd-menu-rc

# my variables
menuLocationY=110
let numLinksPerColumn=8
text_locX=10

createSecondMenuArea(){
	#dnlam: make two white areas
	let secondColumnOffset=310
	let secondWhiteAreaX=$menu_location_x+$secondColumnOffset
	let secondWhiteAreaX2=$menuright+$secondColumnOffset

	convert -size ${width}x$menuh -quality 100 xc:transparent -depth 8 -fill white \
		-draw "roundRectangle $secondWhiteAreaX,$menu_location_y,$secondWhiteAreaX2,$menubottom 20,20" \
		-crop $resolution-0-0 "$1"
}


# --------------- for dvd-menu --------------------------

bg_color='green'
menu_height=36
menu_width=288
menu_location_x=60
menu_location_y=$menuLocationY  # distance of the top of the first menu item to the top of the screen
title_font_size=48
title_location_x=40
title_location_y=30

